services:
  - type: web
    name: polissia-science-park
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Science Park
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_FORCE_HTTPS
        value: true
      - key: APP_LOCALE
        value: uk
      - key: APP_FALLBACK_LOCALE
        value: uk
      - key: APP_FAKER_LOCALE
        value: uk_UA
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: RUN_MIGRATIONS
        value: true
      - key: ADMIN_NAME
        value: Administrator
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
