@extends('admin.layouts.app')
@section('title', $newsItem->exists ? 'Редагувати новину' : 'Додати новину')
@section('content')
<div class="topbar"><h1>{{ $newsItem->exists ? 'Редагувати новину' : 'Додати новину' }}</h1><a class="btn secondary" href="{{ route('admin.news.index') }}">Назад</a></div>
<form class="card form" method="post" enctype="multipart/form-data" action="{{ $newsItem->exists ? route('admin.news.update',$newsItem) : route('admin.news.store') }}">@csrf @if($newsItem->exists) @method('PUT') @endif
<div class="grid grid-2"><div class="field"><label>Категорія</label><select name="news_category_id" required><option value="">Оберіть категорію</option>@foreach($categories as $cat)<option value="{{ $cat->id }}" @selected(old('news_category_id',$newsItem->news_category_id) == $cat->id)>{{ $cat->name_ua }}</option>@endforeach</select></div><div class="field"><label>SEO URL / slug</label><input name="slug" maxlength="220" value="{{ old('slug',$newsItem->slug) }}"><div class="help">Якщо порожньо — автоматично з українського заголовка.</div></div></div>
<div class="grid grid-2"><div class="field"><label>Заголовок UA</label><input name="title_ua" maxlength="200" value="{{ old('title_ua',$newsItem->title_ua) }}" required></div><div class="field"><label>Заголовок EN</label><input name="title_en" maxlength="200" value="{{ old('title_en',$newsItem->title_en) }}" required></div></div>
<div class="grid grid-2"><div class="field"><label>Короткий опис UA</label><textarea name="excerpt_ua" maxlength="300" required>{{ old('excerpt_ua',$newsItem->excerpt_ua) }}</textarea></div><div class="field"><label>Короткий опис EN</label><textarea name="excerpt_en" maxlength="300" required>{{ old('excerpt_en',$newsItem->excerpt_en) }}</textarea></div></div>
<div class="grid grid-2"><div class="field"><label>Повний текст UA</label><textarea name="body_ua" style="min-height:220px" required>{{ old('body_ua',$newsItem->body_ua) }}</textarea></div><div class="field"><label>Повний текст EN</label><textarea name="body_en" style="min-height:220px" required>{{ old('body_en',$newsItem->body_en) }}</textarea></div></div>
<div class="grid grid-2"><div class="field"><label>Дата публікації</label><input type="datetime-local" name="published_at" value="{{ old('published_at', $newsItem->published_at ? $newsItem->published_at->format('Y-m-d\\TH:i') : '') }}"><div class="help">Майбутня дата = відкладена публікація. До цієї дати новина не показується.</div></div><div class="field"><label>Порядок</label><input type="number" name="sort_order" min="0" max="255" value="{{ old('sort_order',$newsItem->sort_order ?? 0) }}"></div></div>
<div class="grid grid-2"><div class="field"><label>Головне зображення</label><input type="file" name="image" accept=".jpg,.jpeg,.png,.webp">@if($newsItem->image_path)<p><img class="thumb" src="{{ asset($newsItem->image_path) }}" alt=""></p>@endif</div><div class="field"><label>Додаткова фотогалерея</label><input type="file" name="gallery[]" multiple accept=".jpg,.jpeg,.png,.webp"><div class="help">До 10 фото на одну новину.</div></div></div>
<div class="grid grid-2"><label class="checkbox"><input type="checkbox" name="is_pinned" value="1" @checked(old('is_pinned',$newsItem->is_pinned))> Закріплена / головна новина</label><label class="checkbox"><input type="checkbox" name="is_archived" value="1" @checked(old('is_archived',$newsItem->is_archived))> Архівувати новину</label></div>
@if($newsItem->exists && $newsItem->photos->count())
<div class="field"><label>Поточна галерея</label><div class="gallery">@foreach($newsItem->photos as $photo)<div class="gallery-item"><img src="{{ asset($photo->image_path) }}" alt=""><label class="checkbox"><input type="checkbox" name="delete_photos[]" value="{{ $photo->id }}"> Видалити</label></div>@endforeach</div></div>
@endif
<div><button class="btn gold" type="submit">Зберегти</button></div>
</form>
@endsection
